import drink1 from "../../public/img/Drink1.jpg";
import pateso from "../../public/img/Pateso.jpg";
import combo1 from "../../public/img/Combo.jpg";

const MenuFull = [
  {
    id: 1,
    image: drink1,
    title: "JoyS drink 2",
    price: "30$",
    alt: "JoyS drink",
    descr: "",
    kind: "Coffee",
    name: "flavours",
    value: "Coffee",
  },
  {
    id: 2,
    image: pateso,
    title: "Pateso",
    price: "35$",
    alt: "JoyS pateso pie",
    descr: "",
    kind: "Cakes",
    value: "Cakes",
    name: "flavours",
  },
  {
    id: 3,
    image: drink1,
    title: "JoyS drink 2",
    price: "30$",
    alt: "JoyS drink",
    descr: "",
    kind: "Coffee",
    value: "Coffee",
    name: "flavours",
  },
  {
    id: 4,
    image: pateso,
    title: "Pateso",
    price: "35$",
    alt: "JoyS pateso pie",
    descr: "",
    kind: "Cakes",
    value: "Cakes",
    name: "flavours",
  },
  {
    id: 5,
    image: drink1,
    title: "JoyS drink 2",
    price: "30$",
    alt: "JoyS drink",
    descr: "",
    kind: "Coffee",
    value: "Coffee",
    name: "flavours",
  },
  {
    id: 6,
    image: pateso,
    title: "Pateso",
    price: "35$",
    alt: "JoyS pateso pie",
    descr: "",
    kind: "Cakes",
    value: "Cakes",
    name: "flavours",
  },
  {
    id: 7,
    image: combo1,
    title: "JoyS Combo 1",
    price: "40$",
    alt: "JoyS Combo",
    descr: "Drink + Cake",
    kind: "JoyS Combo",
    value: "JoyS Combo",
    name: "flavours",
  },
  {
    id: 8,
    image: combo1,
    title: "Special JoyS",
    price: "40$",
    alt: "Special JoyS",
    descr: "Drink + Cake 2",
    kind: "Special JoyS",
    value: "Special JoyS",
    name: "flavours",
  },
  {
    id: 9,
    image: drink1,
    title: "JoyS Tea 1",
    price: "30$",
    alt: "JoyS Tea",
    descr: "",
    kind: "Tea",
    name: "flavours",
    value: "Tea",
  },
];

export default MenuFull;
